### PR TITLE
[106X] UL updates: renamed muon ID and ISO SF files; added SingleMuon trigger SF files

### PR DESCRIPTION
**Pull request by MatthiesC**
This Pull Request will start automatic compilation, then making + testing of ntuples:

- Don't want to run any of this? (e.g. only XML files) Remove the @: [ci  skip]

- Only want to compile, but don't make + test ntuples? (e.g. change `CommonModules.cxx`) Remove the @: [only @ compile]

Please include destination branch in title, e.g. `[102X]`, + short meaningful title

Please include an explanation message if it's something more complex than just XML dataset files:

### CODE REVIEW

**Comment by mschrode** [comment]
Thanks @MatthiesC ! For the *renamed* files, are they imported somewhere in the repo, eg a config file, that needs adaption then as well? And for the *added* files, the same, do they need to be added to some config sequence in the repo?

**Comment by mschrode** [comment]
Ah, one more question: how large are the added files?

**Comment by MatthiesC** [comment]
Hi @mschrode! The largest file has a size of 104kB, all files have 1.1MB. The filepaths are defined on user-level, so there are no adjustments to be made to the main code.

The files are read-in by the class `MCMuonScaleFactor` in https://github.com/UHH2/UHH2/blob/RunII_106X_v1/common/include/MCWeight.h#L107

**Comment by mschrode** [comment]
OK, I see, thanks!

**Pull request merged**
