### PR TITLE
V31 in JetCorrections now with DE combined

### PR DESCRIPTION
**Pull request by garbersc**
I forgot, that I had to change the filenames for DE combined...

### CODE REVIEW

**Comment by garbersc** [comment]
removed 2016 JEC definitions and split Data and MC. @karavdin Is that what you meant yesterday?

**Comment by garbersc** [comment]
sorry for merging before letting you check the code. I hope everything is fine

**Comment by karavdin** [comment]
@garbersc , I belive you don't need MC in DEFINE_JERFILES_DEcombined:
https://github.com/UHH2/UHH2/blob/RunII_94X_v2/common/include/JetCorrections.h#L60-L61

Could you also re-name "DEFINE_JERFILES_DEcombined" to "DEFINE_JERFILES_DATA_DEcombined", please?

**Comment by anmalara** [comment]
Another comment. Since those are temporary tests, it's more straightforward to leave the same definition of all the run, and apply the same correction to the multiple runs. ie, runCD with correction for CDcombined, should go to runC,runD separately both applying the correction for CDcombined. you can also include runCD. this prevents changes in the module we are running. Thanks

**Pull request merged**
