### PR TITLE
JER_SF for JEC_V_24

### PR DESCRIPTION
**Pull request by anmalara**

### CODE REVIEW

**Comment by anmalara** [comment]
Stat + syst

**Comment by raggleton** [comment]
Compilation failed:

```
src/JetCorrections.cxx:1206:41: error: 'JERSmearing::SF_13TeV_Fall17_V10' should have been declared inside 'JERSmearing'
 const JERSmearing::SFtype1 JERSmearing::SF_13TeV_Fall17_V10 = {
                                         ^~~~~~~~~~~~~~~~~~~
src/JetCorrections.cxx:1227:41: error: 'JERSmearing::SF_13TeV_Fall17_V24' should have been declared inside 'JERSmearing'
 const JERSmearing::SFtype1 JERSmearing::SF_13TeV_Fall17_V24 = {
                                         ^~~~~~~~~~~~~~~~~~~
../Makefile.common:119: recipe for target 'obj/JetCorrections.o' failed
```

**Comment by karavdin** [comment]
@anmalara, seems like commit of *.h file is missing

**Comment by raggleton** [comment]
Yeah, you need to modify here: https://github.com/UHH2/UHH2/blob/03968e700da4cc73fce114c9701a47832b433de1/common/include/JetCorrections.h#L554

**Comment by raggleton** [comment]
Thanks, starting compilation tests again

**Comment by anmalara** [comment]
Done. I forgot to commit the header.

**Pull request merged**
