### PR TITLE
delete 102X_v1 2017 TstarTstar samples

### PR DESCRIPTION
**Pull request by finnlabe**
This Pull Request will start automatic compilation, then making + testing of ntuples:

- Don't want to run any of this? (e.g. only XML files) Remove the @: [ci  skip]

- Only want to compile, but don't make + test ntuples? (e.g. change `CommonModules.cxx`) Remove the @: [only @ compile]

Please include destination branch in title, e.g. `[102X]`, + short meaningful title

Please include an explanation message if it's something more complex than just XML dataset files:
These samples were reprocessed and are now available in 102X_v1.

### CODE REVIEW

**Comment by anmalara** [comment]
@raggleton I think those files are into Anastasia folder. Can you remove them? Same for the other PR in uhh2-dataset.

**Comment by raggleton** [comment]
I'm afraid I can't remove the files in someone else's user directory, only those in the group directory

**Comment by anmalara** [comment]
Do we leave there then? I guess her area will be deleted at some point.

**Comment by raggleton** [comment]
Yeah, I'm assuming as a signal sample it's not that big anyway

**Pull request merged**
