### PR TITLE
[106X] Update to CMSSW_10_6_26

### PR DESCRIPTION
**Pull request by finnlabe**
Switching to new CMSSW version, needed for egamma postrecotools. It compiled for me locally, and a few exemplary ntuplewriters worked, lets see what the full tests say.

### CODE REVIEW

**Comment by finnlabe** [comment]
Looks like this works! Should we then just merge, or is there anything else to check?

**Comment by mschrode** [comment]
Thanks @finnlabe ! We can then rebase #1571 to this new HEAD and see if that works

**Comment by finnlabe** [comment]
Great! The label for #1571 is still on "running" do the tests need to be stopped before doing that?

**Comment by mschrode** [comment]
Sorry, I missed this. No, you can start new tests any time - but I saw you did this already :)

**Pull request merged**
