### PR TITLE
Bug fix crash in MCPileupReweight

### PR DESCRIPTION
**Pull request by anmalara**
Don't know why this was still not fixed. I remember we did the same change long time ago.
It prevents the crash of the code if empty bin is found.

[only compile]

### CODE REVIEW

**Comment by raggleton** [comment]
Yeah, I seem to recall we fixed a similar bug a while back... tbh the best way to handle this sort of could-return-prematurely behaviour, is to do the `event.set(handle, 0)` right at the start of the method, before anything can `return`, and then later call `event.set` again if it gets to the right values. This way it was at least set once to some default value, and we don't have to remember to add it in every time we want to do `return false`

**Comment by raggleton** [comment]
Now it's saying there are merge conflicts...

**Comment by anmalara** [comment]
it’s an indentation problem. I saw that only online but not on my terminal.
I’m in a meeting but I’ll fix it soon. Sorry about that.

**Comment by anmalara** [comment]
Ok. Finally I fixed it. Sorry for the many attempts. I think we can merge it now.

**Pull request merged**
