### PR TITLE
[102X] Change default value of m_genjet_index, add getter for genjet_index

### PR DESCRIPTION
**Pull request by raggleton**
Changed to -1 as 0 is a valid index

### CODE REVIEW

**Comment by raggleton** [comment]
Useless without a getter as well, adding one and redoing pipeline

**Comment by karavdin** [comment]
Hists don't look like desired change:
https://uhh2-integration.web.cern.ch/UHH2integration/test1107/mc_2017_TTHadronic_figs/slimmedJets.genjet_index.pdf
Is default overwritten somewhere?

**Comment by raggleton** [comment]
Urgh somehow my 2nd commit changed it back to 0. Will fix and rerun tests

**Comment by raggleton** [comment]
Finally, looks like they're all set at -1

(Side note: they count as "Added Hists" and not "Diff" since there was no getter before, which is how the automated plotter works)

**Pull request merged**
