### PR TITLE
[106X] added flag for photon sources and switched them on (as default)

### PR DESCRIPTION
**Pull request by jabuschh**
This PR fixes the empty m_source_candidates branch (with the leaves: key, px, py, pz, E) in the slimmedPhotonsUSER collection.
The boolean set to false is replaced by a flag which is switched on as default.
The file size increase for the default UL18 test sample is ~1%.

### CODE REVIEW

**Comment by mschrode** [comment]
Hi @jabuschh , thanks! Looking at the test plots, it seems nothing has changed, though. Which variables should have been added?

**Comment by mschrode** [comment]
Another thing, sorry, I should have mentioned earlier: can you add the new photon switch `save_photon_keys` also [here](https://github.com/UHH2/UHH2/blob/RunII_106X_v1/core/python/optionsParse.py#L42-L45)? This control the automatic plots in the CI, giving the option to produce one set of plots with all optional plots included (`max`) and w/o them.

**Comment by jabuschh** [comment]
> Hi @jabuschh , thanks! Looking at the test plots, it seems nothing has changed, though. Which variables should have been added?

I see... The variables added (leaves: `key, px, py, pz, E`) are stored in the sub-branch `m_source_candidates` in `slimmedPhotonsUSER`. It seems to me that these variables are not plotted during the tests.

> Another thing, sorry, I should have mentioned earlier: can you add the new photon switch `save_photon_keys` also [here](https://github.com/UHH2/UHH2/blob/RunII_106X_v1/core/python/optionsParse.py#L42-L45)? This control the automatic plots in the CI, giving the option to produce one set of plots with all optional plots included (`max`) and w/o them.

Sure, I will do this.

**Comment by mschrode** [comment]
> > Hi @jabuschh , thanks! Looking at the test plots, it seems nothing has changed, though. Which variables should have been added?
> 
> I see... The variables added (leaves: `key, px, py, pz, E`) are stored in the sub-branch `m_source_candidates` in `slimmedPhotonsUSER`. It seems to me that these variables are not plotted during the tests.

Ah OK, makes sense

> 
> > Another thing, sorry, I should have mentioned earlier: can you add the new photon switch `save_photon_keys` also [here](https://github.com/UHH2/UHH2/blob/RunII_106X_v1/core/python/optionsParse.py#L42-L45)? This control the automatic plots in the CI, giving the option to produce one set of plots with all optional plots included (`max`) and w/o them.
> 
> Sure, I will do this.

:+1: thanks

**Comment by jabuschh** [comment]
Ah yes, I just saw that those source candidate plots are available for electrons and muons: `slimmed{Electrons,Muons}USER.source_candidates.{E,key,px,py,pz}.pdf`.
I think we should add the `slimmedPhotonsUSER.source_candidates.{E,key,px,py,pz}` plots to the tests as well then?

**Comment by mschrode** [comment]
> Ah yes, I just saw that those source candidate plots are available for electrons and muons: `slimmed{Electrons,Muons}USER.source_candidates.{E,key,px,py,pz}.pdf`.
> I think we should add the `slimmedPhotonsUSER.source_candidates.{E,key,px,py,pz}` plots to the tests as well then?

OK! Yes, agreed. I need to check how this is done

**Pull request merged**
