### PR TITLE
Save git history of common/UHH2-data/

### PR DESCRIPTION
**Pull request by MatthiesC**
[ci  skip]

Revert some commits from https://github.com/UHH2/UHH2/pull/1603 which moved most files from `common/data/` to `common/UHH2-data/`, and now proplery use `git mv` to rename these files. In the end, this does not change any files. But it prevents losing the git history of these files. In the reverted commits, `git mv` was probably not used but only `mv`, `cp` or similar, so that git thought that some files were deleted and new ones were pushed (instead of just moved)

### CODE REVIEW

**Comment by MatthiesC** [comment]
As stated in https://github.com/isaacs/github/issues/900 it apparently won't restore the git history shown on GitHub because GitHub does not support showing the history from before renames. But it works locally doing `git log --follow <file>`

**Comment by mschrode** [comment]
Hi @MatthiesC , repeating in my own words to make sure I understand: so this PR will change the git history but only when I look at it in the local clone, not on the github webpage?

**Comment by MatthiesC** [comment]
Yes. The history is also stored on GitHub somehow but not visible.

**Comment by MatthiesC** [comment]
To verify you can locally do e.g. `git log --follow ../../common/UHH2-data/UL18/DeepCSV_106XUL18SF.csv` before and after pulling the commits from this PR.

Before:
```
commit e963b308e4b2ebd534040cb7d56e175685b1cf40
Author: apaasch <...>
Date:   Thu Nov 4 16:51:05 2021 +0100

    avoid large tarball
```

After:
```
commit 1d3cc839591b8ae49e2ef20807ab5fe66ca3d2d3 (HEAD -> safe_uhh2_data_history, fork/safe_uhh2_data_history)
Author: Christopher Matthies <...>
Date:   Thu Nov 18 18:17:24 2021 +0100

    properly used git mv to move files from common/data to common/UHH2-data

commit 78836347c626fd9b6305cba820dc632d036ba5f7
Author: Christopher Matthies <...>
Date:   Thu Nov 18 18:13:48 2021 +0100

    Revert "removed files for crab"
    
    This reverts commit 3c4a9be00afd971d84e1259e3386fb50e911e9d6.

commit 83e8ce7ca70b261553926d8fdc97ed39af362565
Author: Christopher Matthies <...>
Date:   Thu Nov 18 18:11:37 2021 +0100

    Revert "Revert "removed files for crab""
    
    This reverts commit 90038ae719687893d306452f9cd7816bc3f4a320.

commit 90038ae719687893d306452f9cd7816bc3f4a320
Author: Christopher Matthies <...>
Date:   Thu Nov 18 18:10:49 2021 +0100

    Revert "removed files for crab"
    
    This reverts commit 3c4a9be00afd971d84e1259e3386fb50e911e9d6.

commit 3c4a9be00afd971d84e1259e3386fb50e911e9d6
Author: apaasch <...>
Date:   Thu Nov 4 16:50:04 2021 +0100

    removed files for crab

commit e1f6a97ea8bf5907b94b23836abe9ee3c3d58ec0
Author: Christopher Matthies <...>
Date:   Wed Feb 17 12:10:23 2021 +0100

    DeepCSV+DeepJet SF files for UL17+UL18
```

(Sorry for the double-revert)

Now you can again see which person uploaded the file initially (and when and with which commit). I stumbled upon this issue when I wanted to check whether the Golden JSON files are still valid

**Pull request merged**
