### PR TITLE
[102X] Commented out an empty root file in SingleMuon2016_RunB

### PR DESCRIPTION
**Pull request by skottkej**
[ci skip]

### CODE REVIEW

**Comment by raggleton** [comment]
Hi, since the RunB ver1 and ver2 files got merged in #1320 into one XML file, could you update this PR accordingly? Thanks

**Comment by skottkej** [comment]
Should now be updated.

**Comment by raggleton** [comment]
In the new RunB file, the number of entries looks like it's just form the old ver2 file? Should it be 1422819 + 246440440 = 247863259 ?

**Comment by skottkej** [comment]
Yes you are right, I just fixed it!

**Pull request merged**
