### PR TITLE
Run ii 94 x v2

### PR DESCRIPTION
**Pull request by anmalara**

### CODE REVIEW

**Comment by raggleton** [comment]
Compilation failed:

```
src/JetCorrections.cxx:940:1: error: version control conflict marker in file
 <<<<<<< HEAD
 ^~~~~~~
```

**Comment by karavdin** [comment]
SFs were already merged by Christoph. Could you check if they are fine in 94X_v2 and create PR if anything is not right, please?

**Comment by anmalara** [comment]
Now it should work.
I haven't updated with the latest commit.
Added also SF for RunF_ECAL related to Run2017F_09May2018.

**Comment by raggleton** [comment]
OK compiles fine now

**Pull request merged**
