### PR TITLE
[106X] UL JetPFID, UL17/18 DeepCSV/DeepJet WPs + SFs, UL17/18 golden JSONs, UL16/17/18 Muon ID/ISO SFs

### PR DESCRIPTION
**Pull request by MatthiesC**
This Pull Request will start automatic compilation, then making + testing of ntuples:

- Don't want to run any of this? (e.g. only XML files) Remove the @: [ci @ skip]

- Only want to compile, but don't make + test ntuples? (e.g. change `CommonModules.cxx`) Remove the @: [only compile]

Please include destination branch in title, e.g. `[102X]`, + short meaningful title

Please include an explanation message if it's something more complex than just XML dataset files:

### CODE REVIEW

**Comment by anmalara** [comment]
Can you also implement the LepVeto ID?

**Comment by MatthiesC** [comment]
@anmalara Yes

**Comment by anmalara** [comment]
Can you also add as a comment in the PR, the exact path of the JSON file you used and the command?
It's quite useful to keep track, since these info are not specified in the name usually. Thanks :)

**Comment by MatthiesC** [comment]
I followed the steps here: https://github.com/UHH2/UHH2/wiki/Creating-&-using-luminosity-ROOT-file-in-SFrame
I used the PHYSICS normtag (not the BRIL normtag as stated in the above wiki entry) as recommended here: https://twiki.cern.ch/twiki/bin/view/CMS/TWikiLUM#CurRec

Golden JSONs for UL17 and UL18 have been produced with
`brilcalc lumi --normtag /cvmfs/cms-bril.cern.ch/cms-lumi-pog/Normtags/normtag_PHYSICS.json -i /afs/cern.ch/cms/CAF/CMSCOMM/COMM_DQM/certification/Collisions17/13TeV/Legacy_2017/Cert_294927-306462_13TeV_UL2017_Collisions17_GoldenJSON.txt`
and
`brilcalc lumi --normtag /cvmfs/cms-bril.cern.ch/cms-lumi-pog/Normtags/normtag_PHYSICS.json -i /afs/cern.ch/cms/CAF/CMSCOMM/COMM_DQM/certification/Collisions18/13TeV/Legacy_2018/Cert_314472-325175_13TeV_Legacy2018_Collisions18_JSON.txt`

I did not produce UL16 golden JSON yet. Running the following command resulted in a warning ("Warning: problems found in merging -i and --normtag selections"):
`brilcalc lumi --normtag /cvmfs/cms-bril.cern.ch/cms-lumi-pog/Normtags/normtag_PHYSICS.json -i /afs/cern.ch/cms/CAF/CMSCOMM/COMM_DQM/certification/Collisions16/13TeV/Legacy_2016/Cert_271036-284044_13TeV_Legacy2016_Collisions16_JSON.txt`

**Comment by MatthiesC** [comment]
Added LepVetoID for UL as stated in the latest commit. Alongside of it, I fixed the LepVetoID for non-UL 2018: One actually needs two WPs there, one for CHS and one for PUPPI jets

**Pull request merged**
