### PR TITLE
fixes for Modified MET 

### PR DESCRIPTION
**Pull request by karavdin**
switch to raw jet pt in correct_MET, adding 23SepV4 JEC used for testing and more debugging in PrintingModules. Switch on L1Seed info, which should be enabled for 2017 processing by default.
MET tests with this branch:
https://www.dropbox.com/s/0xqzo0vglstvstu/20181113_MET_recorrection_test_wDijet_for_2017_ModifiedTypeI_94Xv3.pdf?dl=0

### CODE REVIEW

**Comment by raggleton** [comment]
I'm just trying to trigger an automated build with the labels, please bear with me...

**Comment by karavdin** [comment]
No problem, automated build test might be more useful than any of the change in this commit :)

**Comment by raggleton** [comment]
BTW prior warning - it does the whole `install.sh` script and has to compile everything, so will take a little while ⏳

**Comment by raggleton** [comment]
Tests failed to report that there's a bug in `ntuplewriter_addL1seed_woHOTVR_woTopJets_wTriggerObjects_wLowPtjets_wXCONE_wGenParticles_wModifiedMET_DATA ` and `ntuplewriter_addL1seed_woHOTVR_woTopJets_wTriggerObjects_wLowPtjets_wXCONE_wGenParticles_wModifiedMET_MC`, the `fixEE2017Params` in those files have incorrect capitalisation

**Comment by karavdin** [comment]
bunch of ntuplewrite config is leftover from old branch, removed them from this brand clean branch.

**Comment by raggleton** [comment]
Cool thanks

**Pull request merged**
