### PR TITLE
[UHH2-data/UL18] Update golden json for UL18

### PR DESCRIPTION
**Pull request by bonanomi**
This PR aims at solving https://github.com/UHH2/UHH2/issues/1667.

The lumi golden json for UL18 has been updated in the context of B2G-23-006 object review, where it has been pointed out that the golden json we were using contained two extra lumi sections. The golden json included in this PR corresponds to the centrally recommended one:

`/afs/cern.ch/cms/CAF/CMSCOMM/COMM_DQM/certification/Collisions18/13TeV/Legacy_2018/Cert_314472-325175_13TeV_Legacy2018_Collisions18_JSON.txt`

and the `.root` files with the PU profiles for Data (nominal and \pm 1 sigma min-bias) and MC have been produced using [CreatePileupHist.py](https://github.com/UHH2/UHH2/blob/RunII_106X_v2/scripts/CreatePileupHist.py).

This Pull Request will start automatic compilation, then making + testing of ntuples:

- Don't want to run any of this? (e.g. only XML files) Remove the @: [ci @ skip]

- Only want to compile, but don't make + test ntuples? (e.g. change `CommonModules.cxx`) Remove the @: [only @ compile]

Please include destination branch in title, e.g. `[102X]`, + short meaningful title

Please include an explanation message if it's something more complex than just XML dataset files:

### CODE REVIEW

**Comment by danielhundhausen** [comment]
@finnlabe can you merge this for us?

**Comment by finnlabe** [comment]
Sure, but I do have one request: could we add a bit of info to this MR (ideally to the initial description)? Some documentation on where these files come from, what the change is... Just for the sake of keeping things well documented.

**Comment by bonanomi** [comment]
> Sure, but I do have one request: could we add a bit of info to this MR (ideally to the initial description)? Some documentation on where these files come from, what the change is... Just for the sake of keeping things well documented.

Hi @finnlabe, I've added few details to the description of the PR to specify where the changes come from.

**Comment by finnlabe** [comment]
Thanks @bonanomi ! I'll merge this then.

**Pull request merged**
