### PR TITLE
[106X_v2] updating crab_template.py to fix multicrab with newest crab3 version

### PR DESCRIPTION
**Pull request by stalbrec**
removing unnecessary line with doc string for UHH2 Crab ConfigSection, since this results in error in newest version of crab.

[ci skip]

### CODE REVIEW

**Comment by stalbrec** [comment]
There seems to be another problem when using the newest crab version. I will look into this and add possible changes to this PR

**Comment by stalbrec** [comment]
Okay this shoul've fixed this, but we should probably think about changing the way we get our per-dataset options to the right place in `CrabScript.py`.
The way i implemented it is pretty ugly and has now proven to break easily with crab changing ever so slightly

**Comment by MatthiesC** [comment]
Okay, thanks for this. I tested your PR and multicrab's submitting, status checking etc. works again as expected. I am in favor of merging.
Right now, everything works as expected and I am not sure if changing everything now is worth the effort ("never change a running system")

**Comment by mschrode** [comment]
OK I will merge now to fix the workflow for now. More fundamental changes can come later in separate PRs.

**Pull request merged**
